# Download from one, upload to all.
[rclone]
downloadSource = ["source1:", "source2:"]
uploadDestination = ["destination1:", "destination2:"]

[broker]

  # Settings for the broker to listen messages from
  # Used in @worker
  [broker.inbound]
  protocol = "amqp"
  host = "localhost"
  port = "5672"
  username = ""
  password = ""
  heartbeat = 60 # seconds
  vhost = "/"
  queue = ""
  closeMessage = "Closed via management plugin"

  # Settings for the broker to send messages to
  # Used in @notification
  [broker.outbound]
  protocol = "amqp"
  host = "localhost"
  port = "5672"
  username = ""
  password = ""
  heartbeat = 60 # seconds
  vhost = "/"
  exchange = ""
  routingKey = ""
  closeMessage = "Closed via management plugin"

# Settings for retry attempts when failed to connect to broker.
# However, if the connection was closed by an operator, these settings 
# will be irrelevant and no retry attempts will be made. More specifically,
# if the message sent by the operator is equals to "closeMessage".
# The following formula is used to calculate interval in-between retries
# Math.min(random * minTimeout * Math.pow(factor, attempt), maxTimeout)
# Read more about Math.min() and Math.pow() here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math
[retry]
retries = 10 # Max number of retry attempts. Keep this number low or might run out of memory.
factor = 2 # Exponential back-off factor.
minTimeout = 60000 # milliseconds. Can NOT be less than 1 (min setTimeout limit).
maxTimeout = 3600000 # milliseconds. Can NOT be larger than 2147483647 (max setTimeout limit).
randomize = false
forever = true # if true, "retries" is ignored.
unref = false # Whether to unref the setTimeout's. Read more about it here https://nodejs.org/api/timers.html#timers_timeout_unref
maxRetryTime = 0 # milliseconds. 0 means Infinity.

# In the event that a message fails to reach the outbound broker,
# send a message to discord webhook instead.
[discord]
webhooks = [
  # "name" is only relevant for logging
  { name = "...", url = "..." },
  { name = "...", url = "..." },
]

# Flags when running child processes
[flags]
rclone = "--bwlimit 40M --config conf/rclone.conf"